"use client"
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { EnableNextAppRouterViewTransitions } from "use-view-transitions/next";
import { AutoViewTransitionsOnClick } from "use-view-transitions/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* This would make sure transition's new state is captured at the end of the route change. */}
      <EnableNextAppRouterViewTransitions />

      {/* This captures link clicks and injects a view transition. */}
      <AutoViewTransitionsOnClick match="a[href]" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
